# Form implementation generated from reading ui file 'add_parent_contacts_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_ParentContacts(object):
    def setupUi(self, Dialog_ParentContacts):
        Dialog_ParentContacts.setObjectName("Dialog_ParentContacts")
        Dialog_ParentContacts.resize(403, 173)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog_ParentContacts)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=Dialog_ParentContacts)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_ParentPhone = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_ParentPhone.setFont(font)
        self.lineEdit_ParentPhone.setObjectName("lineEdit_ParentPhone")
        self.horizontalLayout.addWidget(self.lineEdit_ParentPhone)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_ParentEmail = QtWidgets.QLineEdit(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_ParentEmail.setFont(font)
        self.lineEdit_ParentEmail.setObjectName("lineEdit_ParentEmail")
        self.horizontalLayout_2.addWidget(self.lineEdit_ParentEmail)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.button_box = QtWidgets.QDialogButtonBox(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.button_box.setFont(font)
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Save)
        self.button_box.setObjectName("button_box")
        self.verticalLayout.addWidget(self.button_box)
        self.verticalLayout_2.addWidget(self.frame)

        self.retranslateUi(Dialog_ParentContacts)
        self.button_box.accepted.connect(Dialog_ParentContacts.accept) # type: ignore
        self.button_box.rejected.connect(Dialog_ParentContacts.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_ParentContacts)

    def retranslateUi(self, Dialog_ParentContacts):
        _translate = QtCore.QCoreApplication.translate
        Dialog_ParentContacts.setWindowTitle(_translate("Dialog_ParentContacts", "Контакты"))
        self.label.setText(_translate("Dialog_ParentContacts", "Введите данные"))
        self.label_2.setText(_translate("Dialog_ParentContacts", "Телефон"))
        self.label_3.setText(_translate("Dialog_ParentContacts", "Email"))
