# Form implementation generated from reading ui file 'date_input_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DateInputDialog(object):
    def setupUi(self, DateInputDialog):
        DateInputDialog.setObjectName("DateInputDialog")
        DateInputDialog.resize(463, 122)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DateInputDialog)
        self.buttonBox.setGeometry(QtCore.QRect(110, 70, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(parent=DateInputDialog)
        self.widget.setGeometry(QtCore.QRect(20, 30, 432, 24))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_InputDate = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_InputDate.setFont(font)
        self.lineEdit_InputDate.setObjectName("lineEdit_InputDate")
        self.horizontalLayout.addWidget(self.lineEdit_InputDate)

        self.retranslateUi(DateInputDialog)
        self.buttonBox.accepted.connect(DateInputDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DateInputDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DateInputDialog)

    def retranslateUi(self, DateInputDialog):
        _translate = QtCore.QCoreApplication.translate
        DateInputDialog.setWindowTitle(_translate("DateInputDialog", "Введите дату"))
        self.label.setText(_translate("DateInputDialog", "Введите дату  ( в формате ДД.MM.ГГГГ):"))
