# Form implementation generated from reading ui file 'delete_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteDialog(object):
    def setupUi(self, DeleteDialog):
        DeleteDialog.setObjectName("DeleteDialog")
        DeleteDialog.resize(507, 122)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DeleteDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_TextOne = QtWidgets.QLabel(parent=DeleteDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_TextOne.setFont(font)
        self.label_TextOne.setText("")
        self.label_TextOne.setObjectName("label_TextOne")
        self.horizontalLayout_2.addWidget(self.label_TextOne)
        self.label_DeleteDataOne = QtWidgets.QLabel(parent=DeleteDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_DeleteDataOne.setFont(font)
        self.label_DeleteDataOne.setText("")
        self.label_DeleteDataOne.setObjectName("label_DeleteDataOne")
        self.horizontalLayout_2.addWidget(self.label_DeleteDataOne)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_TextTwo = QtWidgets.QLabel(parent=DeleteDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_TextTwo.setFont(font)
        self.label_TextTwo.setText("")
        self.label_TextTwo.setObjectName("label_TextTwo")
        self.horizontalLayout.addWidget(self.label_TextTwo)
        self.label_DeleteDataTwo = QtWidgets.QLabel(parent=DeleteDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_DeleteDataTwo.setFont(font)
        self.label_DeleteDataTwo.setText("")
        self.label_DeleteDataTwo.setObjectName("label_DeleteDataTwo")
        self.horizontalLayout.addWidget(self.label_DeleteDataTwo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DeleteDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(DeleteDialog)
        self.buttonBox.accepted.connect(DeleteDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DeleteDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DeleteDialog)

    def retranslateUi(self, DeleteDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteDialog.setWindowTitle(_translate("DeleteDialog", "Удаление записи"))
