# Form implementation generated from reading ui file 'delete_invoice_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DeleteInvoiceDialog(object):
    def setupUi(self, DeleteInvoiceDialog):
        DeleteInvoiceDialog.setObjectName("DeleteInvoiceDialog")
        DeleteInvoiceDialog.resize(507, 122)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteInvoiceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=DeleteInvoiceDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_DeleteMonthName = QtWidgets.QLabel(parent=DeleteInvoiceDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_DeleteMonthName.setFont(font)
        self.label_DeleteMonthName.setText("")
        self.label_DeleteMonthName.setObjectName("label_DeleteMonthName")
        self.horizontalLayout.addWidget(self.label_DeleteMonthName)
        self.label_2 = QtWidgets.QLabel(parent=DeleteInvoiceDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_DeleteInvoiceSum = QtWidgets.QLabel(parent=DeleteInvoiceDialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_DeleteInvoiceSum.setFont(font)
        self.label_DeleteInvoiceSum.setText("")
        self.label_DeleteInvoiceSum.setObjectName("label_DeleteInvoiceSum")
        self.horizontalLayout.addWidget(self.label_DeleteInvoiceSum)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=DeleteInvoiceDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(DeleteInvoiceDialog)
        self.buttonBox.accepted.connect(DeleteInvoiceDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(DeleteInvoiceDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DeleteInvoiceDialog)

    def retranslateUi(self, DeleteInvoiceDialog):
        _translate = QtCore.QCoreApplication.translate
        DeleteInvoiceDialog.setWindowTitle(_translate("DeleteInvoiceDialog", "Удаление квитанции"))
        self.label.setText(_translate("DeleteInvoiceDialog", "Удалить квитанцию за"))
        self.label_2.setText(_translate("DeleteInvoiceDialog", "на сумму"))
