# Form implementation generated from reading ui file 'teacher_choice_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TeacherChoice(object):
    def setupUi(self, TeacherChoice):
        TeacherChoice.setObjectName("TeacherChoice")
        TeacherChoice.resize(581, 122)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        TeacherChoice.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(TeacherChoice)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=TeacherChoice)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_TeacherChoice = QtWidgets.QComboBox(parent=TeacherChoice)
        self.comboBox_TeacherChoice.setObjectName("comboBox_TeacherChoice")
        self.horizontalLayout.addWidget(self.comboBox_TeacherChoice)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=TeacherChoice)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(TeacherChoice)
        self.buttonBox.accepted.connect(TeacherChoice.accept) # type: ignore
        self.buttonBox.rejected.connect(TeacherChoice.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(TeacherChoice)

    def retranslateUi(self, TeacherChoice):
        _translate = QtCore.QCoreApplication.translate
        TeacherChoice.setWindowTitle(_translate("TeacherChoice", "Выбор преподавателя"))
        self.label.setText(_translate("TeacherChoice", "Выберите ФИО преподавателя"))
